package com.zd.crmbatch.business.mssqlshare.entity;
// default package
// Generated 2018-4-24 9:41:14 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Tclientgroupfee generated by hbm2java
 */
@Table(name="TClientGroupFee")
@Entity
@IdClass(TClientGroupFeePk.class)
public class TClientGroupFee{

	private String FClientNo;
	private int FCommodityGroupID;
	private BigDecimal FbFee;
	private BigDecimal FdFee;
	private String fModifyDate;

	@Id
	@Column(name="FClientNo")
	public String getFClientNo() {
		return FClientNo;
	}
	public void setFClientNo(String fClientNo) {
		FClientNo = fClientNo;
	}
	@Id
	@Column(name="FCommodityGroupID")
	public int getFCommodityGroupID() {
		return FCommodityGroupID;
	}
	public void setFCommodityGroupID(int fCommodityGroupID) {
		FCommodityGroupID = fCommodityGroupID;
	}
	@Column(name="FbFee")
	public BigDecimal getFbFee() {
		return FbFee;
	}
	public void setFbFee(BigDecimal fbFee) {
		FbFee = fbFee;
	}
	@Column(name="FdFee")
	public BigDecimal getFdFee() {
		return FdFee;
	}
	public void setFdFee(BigDecimal fdFee) {
		FdFee = fdFee;
	}
	@Column(name="FModifyDate")
	public String getfModifyDate() {
		return fModifyDate;
	}
	public void setfModifyDate(String fModifyDate) {
		this.fModifyDate = fModifyDate;
	}
	

}
