package com.zd.crmbatch.business.mssqlshare.entity;
// default package
// Generated 2018-4-24 9:41:14 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Tcommodity generated by hbm2java
 */
@Table(name="TCommodity")
@Entity
@IdClass(TcommodityPk.class)
public class TCommodity{

	private int FCommodityID;
	private int FExchangeID;
	private String FCommodityNo;
	private String FCommodityType;
	private String FName;
	private String FEnabled;
	private String FRegDate;
	private String FCurrencyNo;
	private BigDecimal FProductDot;
	private BigDecimal FUpperTick;
	private Integer FLowerTick;
	private String FUpperNo;
	private String FCashDelivery;
	private Integer FDeliveryDate;
	private String FRemark;
	private Integer FDotNum;
	private BigDecimal FContractSize;
	private Integer FXDMax;
	private String FUpperNoB1;
	private String FUpperNoB2;
	private String FUpperU;
	private Integer FStrikeCommodityId;
	private String FOptionType;
	private String ETS;
	private String FTOneTime;
	private BigDecimal FUpperTick2;
	private BigDecimal FTickPrice;
	private String FExchangeNo2;
	private String FT1ISTSettle;
	private String FEnName;
	private String FOptionStyle;
	private String FRecommend;
	private String FFutureType;
	private Integer FLever;
	private Integer FDayFill;
	@Id
	@Column(name="FCommodityID")
	public int getFCommodityID() {
		return FCommodityID;
	}
	public void setFCommodityID(int fCommodityID) {
		FCommodityID = fCommodityID;
	}
	@Id
	@Column(name="FExchangeID")
	public int getFExchangeID() {
		return FExchangeID;
	}
	public void setFExchangeID(int fExchangeID) {
		FExchangeID = fExchangeID;
	}
	@Id
	@Column(name="FCommodityNo")
	public String getFCommodityNo() {
		return FCommodityNo;
	}
	public void setFCommodityNo(String fCommodityNo) {
		FCommodityNo = fCommodityNo;
	}
	@Column(name="FCommodityType")
	public String getFCommodityType() {
		return FCommodityType;
	}
	public void setFCommodityType(String fCommodityType) {
		FCommodityType = fCommodityType;
	}
	@Column(name="FName")
	public String getFName() {
		return FName;
	}
	public void setFName(String fName) {
		FName = fName;
	}
	@Column(name="FEnabled")
	public String getFEnabled() {
		return FEnabled;
	}
	public void setFEnabled(String fEnabled) {
		FEnabled = fEnabled;
	}
	@Column(name="FRegDate")
	public String getFRegDate() {
		return FRegDate;
	}
	public void setFRegDate(String fRegDate) {
		FRegDate = fRegDate;
	}
	@Column(name="FCurrencyNo")
	public String getFCurrencyNo() {
		return FCurrencyNo;
	}
	public void setFCurrencyNo(String fCurrencyNo) {
		FCurrencyNo = fCurrencyNo;
	}
	@Column(name="FProductDot")
	public BigDecimal getFProductDot() {
		return FProductDot;
	}
	public void setFProductDot(BigDecimal fProductDot) {
		FProductDot = fProductDot;
	}
	@Column(name="FUpperTick")
	public BigDecimal getFUpperTick() {
		return FUpperTick;
	}
	public void setFUpperTick(BigDecimal fUpperTick) {
		FUpperTick = fUpperTick;
	}
	@Column(name="FLowerTick")
	public Integer getFLowerTick() {
		return FLowerTick;
	}
	public void setFLowerTick(Integer fLowerTick) {
		FLowerTick = fLowerTick;
	}
	@Column(name="FUpperNo")
	public String getFUpperNo() {
		return FUpperNo;
	}
	public void setFUpperNo(String fUpperNo) {
		FUpperNo = fUpperNo;
	}
	@Column(name="FCashDelivery")
	public String getFCashDelivery() {
		return FCashDelivery;
	}
	public void setFCashDelivery(String fCashDelivery) {
		FCashDelivery = fCashDelivery;
	}
	@Column(name="FDeliveryDate")
	public Integer getFDeliveryDate() {
		return FDeliveryDate;
	}
	public void setFDeliveryDate(Integer fDeliveryDate) {
		FDeliveryDate = fDeliveryDate;
	}
	@Column(name="FRemark")
	public String getFRemark() {
		return FRemark;
	}
	public void setFRemark(String fRemark) {
		FRemark = fRemark;
	}
	@Column(name="FDotNum")
	public Integer getFDotNum() {
		return FDotNum;
	}
	public void setFDotNum(Integer fDotNum) {
		FDotNum = fDotNum;
	}
	@Column(name="FContractSize")
	public BigDecimal getFContractSize() {
		return FContractSize;
	}
	public void setFContractSize(BigDecimal fContractSize) {
		FContractSize = fContractSize;
	}
	@Column(name="FXDMax")
	public Integer getFXDMax() {
		return FXDMax;
	}
	public void setFXDMax(Integer fXDMax) {
		FXDMax = fXDMax;
	}
	@Column(name="FUpperNoB1")
	public String getFUpperNoB1() {
		return FUpperNoB1;
	}
	public void setFUpperNoB1(String fUpperNoB1) {
		FUpperNoB1 = fUpperNoB1;
	}
	@Column(name="FUpperNoB2")
	public String getFUpperNoB2() {
		return FUpperNoB2;
	}
	public void setFUpperNoB2(String fUpperNoB2) {
		FUpperNoB2 = fUpperNoB2;
	}
	@Column(name="FUpperU")
	public String getFUpperU() {
		return FUpperU;
	}
	public void setFUpperU(String fUpperU) {
		FUpperU = fUpperU;
	}
	@Column(name="FStrikeCommodityId")
	public Integer getFStrikeCommodityId() {
		return FStrikeCommodityId;
	}
	public void setFStrikeCommodityId(Integer fStrikeCommodityId) {
		FStrikeCommodityId = fStrikeCommodityId;
	}
	@Column(name="FOptionType")
	public String getFOptionType() {
		return FOptionType;
	}
	public void setFOptionType(String fOptionType) {
		FOptionType = fOptionType;
	}
	@Column(name="ETS")
	public String getETS() {
		return ETS;
	}
	public void setETS(String eTS) {
		ETS = eTS;
	}
	@Column(name="FTOneTime")
	public String getFTOneTime() {
		return FTOneTime;
	}
	public void setFTOneTime(String fTOneTime) {
		FTOneTime = fTOneTime;
	}
	@Column(name="FUpperTick2")
	public BigDecimal getFUpperTick2() {
		return FUpperTick2;
	}
	public void setFUpperTick2(BigDecimal fUpperTick2) {
		FUpperTick2 = fUpperTick2;
	}
	@Column(name="FTickPrice")
	public BigDecimal getFTickPrice() {
		return FTickPrice;
	}
	public void setFTickPrice(BigDecimal fTickPrice) {
		FTickPrice = fTickPrice;
	}
	@Column(name="FExchangeNo2")
	public String getFExchangeNo2() {
		return FExchangeNo2;
	}
	public void setFExchangeNo2(String fExchangeNo2) {
		FExchangeNo2 = fExchangeNo2;
	}
	@Column(name="FT1ISTSettle")
	public String getFT1ISTSettle() {
		return FT1ISTSettle;
	}
	public void setFT1ISTSettle(String fT1ISTSettle) {
		FT1ISTSettle = fT1ISTSettle;
	}
	@Column(name="FEnName")
	public String getFEnName() {
		return FEnName;
	}
	public void setFEnName(String fEnName) {
		FEnName = fEnName;
	}
	@Column(name="FOptionStyle")
	public String getFOptionStyle() {
		return FOptionStyle;
	}
	public void setFOptionStyle(String fOptionStyle) {
		FOptionStyle = fOptionStyle;
	}
	@Column(name="FRecommend")
	public String getFRecommend() {
		return FRecommend;
	}
	public void setFRecommend(String fRecommend) {
		FRecommend = fRecommend;
	}
	@Column(name="FFutureType")
	public String getFFutureType() {
		return FFutureType;
	}
	public void setFFutureType(String fFutureType) {
		FFutureType = fFutureType;
	}
	@Column(name="FLever")
	public Integer getFLever() {
		return FLever;
	}
	public void setFLever(Integer fLever) {
		FLever = fLever;
	}
	@Column(name="FDayFill")
	public Integer getFDayFill() {
		return FDayFill;
	}
	public void setFDayFill(Integer fDayFill) {
		FDayFill = fDayFill;
	}


}
