package com.zd.crmbatch.business.mssqlshare.entity;
// default package
// Generated 2018-4-24 9:41:14 by Hibernate Tools 4.3.1

/**
 * TcommodityId generated by hbm2java
 */
public class TcommodityPk implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int FCommodityID;
	private int FExchangeID;
	private String FCommodityNo;
	public TcommodityPk() {
		super();
	}
	public int getFCommodityID() {
		return FCommodityID;
	}
	public void setFCommodityID(int fCommodityID) {
		FCommodityID = fCommodityID;
	}
	public int getFExchangeID() {
		return FExchangeID;
	}
	public void setFExchangeID(int fExchangeID) {
		FExchangeID = fExchangeID;
	}
	public String getFCommodityNo() {
		return FCommodityNo;
	}
	public void setFCommodityNo(String fCommodityNo) {
		FCommodityNo = fCommodityNo;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + FCommodityID;
		result = prime * result + ((FCommodityNo == null) ? 0 : FCommodityNo.hashCode());
		result = prime * result + FExchangeID;
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TcommodityPk other = (TcommodityPk) obj;
		if (FCommodityID != other.FCommodityID)
			return false;
		if (FCommodityNo == null) {
			if (other.FCommodityNo != null)
				return false;
		} else if (!FCommodityNo.equals(other.FCommodityNo))
			return false;
		if (FExchangeID != other.FExchangeID)
			return false;
		return true;
	}


}
