package com.zd.crmbatch.business.entity;
// default package
// Generated 2018-4-23 17:02:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tclientbaseinfo generated by hbm2java
 */
@Table(name="TClientBaseInfo")
@Entity
public class TClientBaseInfo{

	private String FClientNo;
	private String FUpperNo;
	private String FShortName;
	private String FName;
	private String FType;
	private String FState;
	private String FOpenDate;
	private String FCloseDate;
	private String FIdentity;
	private String FPassport;
	private String FTelPhone;
	private String FMobilePhone;
	private String FFax;
	private String FPostNo;
	private String FAddress;
	private String FPostAddress;
	private String FCompanyName;
	private String FCompanyAddress;
	private String FDealMan;
	private String FDealManId;
	private String FCashMan;
	private String FCashManId;
	private String FRemark;
	private String ISsimulation;
	private String FPassword;
	private String FBank;
	private String FAccount;
	private String FSelAll;
	private Integer FSelDepositNum;
	private String FSex;
	private String FExpiryDate;
	private String FMailAddress;
	private String FImage;
	private String FEnabledDate;
	private String FSwapMode;
	private String FMailMode;
	private String FBirthDay;
	private String FSendPhone;
	private String FSalesName;
	private String FUnding;
	private String FSalesPhone;
	private String FEmail;
	private String FCrossAbitrage;
	private String FOpenInfaces;
	private String FFee;
	private String FMultiLogin;
	private String FIreTicket;
	private String FUllStop;
	private String FOption;
	private String FCmemarket;
	private String FCbtMarket;
	private String FComexMarket;
	private String FNymexMarket;
	private String FMarketFeeWay;
	private String FExchangeWay;
	private String FCmemarketFee;
	private String FCbtMarketFee;
	private String FComexMarketFee;
	private String FNymexMarketFee;
	private String FSubClientNo;
	private String FIsSubSettle;
	private String FStock;
	private String FModifyPwdDate;
	private String FApi;
	private String FApiexpiryDate;
	private String FLocation;
	private String FEmail2;
	private String FIceUsMarket;
	private String FIceEcMarket;
	private String FIceEfMarket;
	private String FIceUsMarketFee;
	private String FIceEcMarketFee;
	private String FIceEfMarketFee;
	private String FIceMarketFeeWay;
	private String FRiskLevel;
	private String FAsset;
	private String FOpenName;
	private String FOpenIdentity;
	private String FShareHolder;
	private String FShareCapital;
	private String FRegisteredAddress;
	private String FApiopenTime;
	private String FApicloseTime;
	private String FNationality;
	private String FUseSpan;
	private String FHkexMarcket;
	private String FHkexMarketFee;
	private String MOdifyDate;
	private String FOpenType;
	private String FClientQuestion;
	private String FClientAnswer;
	
	@Id
	@Column(name="FClientNo")
	public String getFClientNo() {
		return FClientNo;
	}
	public void setFClientNo(String fClientNo) {
		FClientNo = fClientNo;
	}
	@Column(name="FUpperNo")
	public String getFUpperNo() {
		return FUpperNo;
	}
	public void setFUpperNo(String fUpperNo) {
		FUpperNo = fUpperNo;
	}
	@Column(name="FShortName")
	public String getFShortName() {
		return FShortName;
	}
	public void setFShortName(String fShortName) {
		FShortName = fShortName;
	}
	@Column(name="FName")
	public String getFName() {
		return FName;
	}
	public void setFName(String fName) {
		FName = fName;
	}
	@Column(name="FType")
	public String getFType() {
		return FType;
	}
	public void setFType(String fType) {
		FType = fType;
	}
	@Column(name="FState")
	public String getFState() {
		return FState;
	}
	public void setFState(String fState) {
		FState = fState;
	}
	@Column(name="FOpenDate")
	public String getFOpenDate() {
		return FOpenDate;
	}
	public void setFOpenDate(String fOpenDate) {
		FOpenDate = fOpenDate;
	}
	@Column(name="FCloseDate")
	public String getFCloseDate() {
		return FCloseDate;
	}
	public void setFCloseDate(String fCloseDate) {
		FCloseDate = fCloseDate;
	}
	@Column(name="FIdentity")
	public String getFIdentity() {
		return FIdentity;
	}
	public void setFIdentity(String fIdentity) {
		FIdentity = fIdentity;
	}
	@Column(name="FPassport")
	public String getFPassport() {
		return FPassport;
	}
	public void setFPassport(String fPassport) {
		FPassport = fPassport;
	}
	@Column(name="FTelPhone")
	public String getFTelPhone() {
		return FTelPhone;
	}
	public void setFTelPhone(String fTelPhone) {
		FTelPhone = fTelPhone;
	}
	@Column(name="FMobilePhone")
	public String getFMobilePhone() {
		return FMobilePhone;
	}
	public void setFMobilePhone(String fMobilePhone) {
		FMobilePhone = fMobilePhone;
	}
	@Column(name="FFax")
	public String getFFax() {
		return FFax;
	}
	public void setFFax(String fFax) {
		FFax = fFax;
	}
	@Column(name="FPostNo")
	public String getFPostNo() {
		return FPostNo;
	}
	public void setFPostNo(String fPostNo) {
		FPostNo = fPostNo;
	}
	@Column(name="FAddress")
	public String getFAddress() {
		return FAddress;
	}
	public void setFAddress(String fAddress) {
		FAddress = fAddress;
	}
	@Column(name="FPostAddress")
	public String getFPostAddress() {
		return FPostAddress;
	}
	public void setFPostAddress(String fPostAddress) {
		FPostAddress = fPostAddress;
	}
	@Column(name="FCompanyName")
	public String getFCompanyName() {
		return FCompanyName;
	}
	public void setFCompanyName(String fCompanyName) {
		FCompanyName = fCompanyName;
	}
	@Column(name="FCompanyAddress")
	public String getFCompanyAddress() {
		return FCompanyAddress;
	}
	public void setFCompanyAddress(String fCompanyAddress) {
		FCompanyAddress = fCompanyAddress;
	}
	@Column(name="FDealMan")
	public String getFDealMan() {
		return FDealMan;
	}
	public void setFDealMan(String fDealMan) {
		FDealMan = fDealMan;
	}
	@Column(name="FDealManID")
	public String getFDealManId() {
		return FDealManId;
	}
	public void setFDealManId(String fDealManId) {
		FDealManId = fDealManId;
	}
	@Column(name="FCashMan")
	public String getFCashMan() {
		return FCashMan;
	}
	public void setFCashMan(String fCashMan) {
		FCashMan = fCashMan;
	}
	@Column(name="FCashManID")
	public String getFCashManId() {
		return FCashManId;
	}
	public void setFCashManId(String fCashManId) {
		FCashManId = fCashManId;
	}
	@Column(name="FRemark")
	public String getFRemark() {
		return FRemark;
	}
	public void setFRemark(String fRemark) {
		FRemark = fRemark;
	}
	@Column(name="isSimulation")
	public String getISsimulation() {
		return ISsimulation;
	}
	public void setISsimulation(String iSsimulation) {
		ISsimulation = iSsimulation;
	}
	@Column(name="FPassword")
	public String getFPassword() {
		return FPassword;
	}
	public void setFPassword(String fPassword) {
		FPassword = fPassword;
	}
	@Column(name="FBank")
	public String getFBank() {
		return FBank;
	}
	public void setFBankk(String fBank) {
		FBank = fBank;
	}
	@Column(name="FAccount")
	public String getFAccount() {
		return FAccount;
	}
	public void setFAccount(String fAccount) {
		FAccount = fAccount;
	}
	@Column(name="FSelAll")
	public String getFSelAll() {
		return FSelAll;
	}
	public void setFSelAll(String fSelAll) {
		FSelAll = fSelAll;
	}
	@Column(name="FSelDepositNum")
	public Integer getFSelDepositNum() {
		return FSelDepositNum;
	}
	public void setFSelDepositNum(Integer fSelDepositNum) {
		FSelDepositNum = fSelDepositNum;
	}
	@Column(name="FSex")
	public String getFSex() {
		return FSex;
	}
	public void setFSexx(String fSex) {
		FSex = fSex;
	}
	@Column(name="FExpiryDate")
	public String getFExpiryDate() {
		return FExpiryDate;
	}
	public void setFExpiryDate(String fExpiryDate) {
		FExpiryDate = fExpiryDate;
	}
	@Column(name="FMailAddress")
	public String getFMailAddress() {
		return FMailAddress;
	}
	public void setFMailAddresss(String fMailAddress) {
		FMailAddress = fMailAddress;
	}
	@Column(name="FImage")
	public String getFImage() {
		return FImage;
	}
	public void setFImage(String fImage) {
		FImage = fImage;
	}
	@Column(name="FEnabledDate")
	public String getFEnabledDate() {
		return FEnabledDate;
	}
	public void setFEnabledDate(String fEnabledDate) {
		FEnabledDate = fEnabledDate;
	}
	@Column(name="FSwapMode")
	public String getFSwapMode() {
		return FSwapMode;
	}
	public void setFSwapMode(String fSwapMode) {
		FSwapMode = fSwapMode;
	}
	@Column(name="FMailMode")
	public String getFMailMode() {
		return FMailMode;
	}
	public void setFMailModee(String fMailMode) {
		FMailMode = fMailMode;
	}
	@Column(name="FBirthDay")
	public String getFBirthDayy() {
		return FBirthDay;
	}
	public void setFBirthDay(String fBirthDay) {
		FBirthDay = fBirthDay;
	}
	@Column(name="FSendPhone")
	public String getFSendPhone() {
		return FSendPhone;
	}
	public void setFSendPhonee(String fSendPhone) {
		FSendPhone = fSendPhone;
	}
	@Column(name="FSalesName")
	public String getFSalesName() {
		return FSalesName;
	}
	public void setFSalesName(String fSalesName) {
		FSalesName = fSalesName;
	}
	@Column(name="Funding")
	public String getFUnding() {
		return FUnding;
	}
	public void setFUnding(String fUnding) {
		FUnding = fUnding;
	}
	@Column(name="FSalesPhone")
	public String getFSalesPhone() {
		return FSalesPhone;
	}
	public void setFSalesPhonee(String fSalesPhone) {
		FSalesPhone = fSalesPhone;
	}
	@Column(name="FEmail")
	public String getFEmail() {
		return FEmail;
	}
	public void setFEmail(String fEmail) {
		FEmail = fEmail;
	}
	@Column(name="FCrossABitrage")
	public String getFCrossAbitrage() {
		return FCrossAbitrage;
	}
	public void setFCrossAbitrage(String fCrossAbitrage) {
		FCrossAbitrage = fCrossAbitrage;
	}
	@Column(name="FOpenInfaces")
	public String getFOpenInfaces() {
		return FOpenInfaces;
	}
	public void setFOpenInfaces(String fOpenInfaces) {
		FOpenInfaces = fOpenInfaces;
	}
	@Column(name="FFee")
	public String getFFee() {
		return FFee;
	}
	public void setFFee(String fFee) {
		FFee = fFee;
	}
	@Column(name="FMultiLogin")
	public String getFMultiLogin() {
		return FMultiLogin;
	}
	public void setFMultiLoginn(String fMultiLogin) {
		FMultiLogin = fMultiLogin;
	}
	@Column(name="FireTicket")
	public String getFIreTicket() {
		return FIreTicket;
	}
	public void setFIreTicket(String fIreTicket) {
		FIreTicket = fIreTicket;
	}
	@Column(name="FullStop")
	public String getFUllStop() {
		return FUllStop;
	}
	public void setFUllStop(String fUllStop) {
		FUllStop = fUllStop;
	}
	@Column(name="FOption")
	public String getFOption() {
		return FOption;
	}
	public void setFOption(String fOption) {
		FOption = fOption;
	}
	@Column(name="FCMEMarket")
	public String getFCmemarket() {
		return FCmemarket;
	}
	public void setFCmemarkett(String fCmemarket) {
		FCmemarket = fCmemarket;
	}
	@Column(name="FCBT_Market")
	public String getFCbtMarket() {
		return FCbtMarket;
	}
	public void setFCbtMarket(String fCbtMarket) {
		FCbtMarket = fCbtMarket;
	}
	@Column(name="FCOMEX_Market")
	public String getFComexMarket() {
		return FComexMarket;
	}
	public void setFComexMarkett(String fComexMarket) {
		FComexMarket = fComexMarket;
	}
	@Column(name="FNYMEX_Market")
	public String getFNymexMarket() {
		return FNymexMarket;
	}
	public void setFNymexMarket(String fNymexMarket) {
		FNymexMarket = fNymexMarket;
	}
	@Column(name="FMarketFeeWay")
	public String getFMarketFeeWay() {
		return FMarketFeeWay;
	}
	public void setFMarketFeeWay(String fMarketFeeWay) {
		FMarketFeeWay = fMarketFeeWay;
	}
	@Column(name="FExchangeWay")
	public String getFExchangeWay() {
		return FExchangeWay;
	}
	public void setFExchangeWay(String fExchangeWay) {
		FExchangeWay = fExchangeWay;
	}
	@Column(name="FCMEMarketFee")
	public String getFCmemarketFee() {
		return FCmemarketFee;
	}
	public void setFCmemarketFee(String fCmemarketFee) {
		FCmemarketFee = fCmemarketFee;
	}
	@Column(name="FCBT_MarketFee")
	public String getFCbtMarketFee() {
		return FCbtMarketFee;
	}
	public void setFCbtMarketFee(String fCbtMarketFee) {
		FCbtMarketFee = fCbtMarketFee;
	}
	@Column(name="FCOMEX_MarketFee")
	public String getFComexMarketFee() {
		return FComexMarketFee;
	}
	public void setFComexMarketFee(String fComexMarketFee) {
		FComexMarketFee = fComexMarketFee;
	}
	@Column(name="FNYMEX_MarketFee")
	public String getFNymexMarketFee() {
		return FNymexMarketFee;
	}
	public void setFNymexMarketFeee(String fNymexMarketFee) {
		FNymexMarketFee = fNymexMarketFee;
	}
	@Column(name="FSubClientNo")
	public String getFSubClientNo() {
		return FSubClientNo;
	}
	public void setFSubClientNo(String fSubClientNo) {
		FSubClientNo = fSubClientNo;
	}
	@Column(name="FIsSubSettle")
	public String getFIsSubSettle() {
		return FIsSubSettle;
	}
	public void setFIsSubSettle(String fIsSubSettle) {
		FIsSubSettle = fIsSubSettle;
	}
	@Column(name="FStock")
	public String getFStock() {
		return FStock;
	}
	public void setFStock(String fStock) {
		FStock = fStock;
	}
	@Column(name="FModifyPwdDate")
	public String getFModifyPwdDate() {
		return FModifyPwdDate;
	}
	public void setFModifyPwdDate(String fModifyPwdDate) {
		FModifyPwdDate = fModifyPwdDate;
	}
	@Column(name="FAPI")
	public String getFApi() {
		return FApi;
	}
	public void setFApi(String fApi) {
		FApi = fApi;
	}
	@Column(name="FAPIExpiryDate")
	public String getFApiexpiryDate() {
		return FApiexpiryDate;
	}
	public void setFApiexpiryDate(String fApiexpiryDate) {
		FApiexpiryDate = fApiexpiryDate;
	}
	@Column(name="FLocation")
	public String getFLocation() {
		return FLocation;
	}
	public void setFLocation(String fLocation) {
		FLocation = fLocation;
	}
	@Column(name="FEmail2")
	public String getFEmail2() {
		return FEmail2;
	}
	public void setFEmail2(String fEmail2) {
		FEmail2 = fEmail2;
	}
	@Column(name="FICE_US_MARKET")
	public String getFIceUsMarket() {
		return FIceUsMarket;
	}
	public void setFIceUsMarket(String fIceUsMarket) {
		FIceUsMarket = fIceUsMarket;
	}
	@Column(name="FICE_EC_MARKET")
	public String getFIceEcMarket() {
		return FIceEcMarket;
	}
	public void setFIceEcMarket(String fIceEcMarket) {
		FIceEcMarket = fIceEcMarket;
	}
	@Column(name="FICE_EF_MARKET")
	public String getFIceEfMarket() {
		return FIceEfMarket;
	}
	public void setFIceEfMarket(String fIceEfMarket) {
		FIceEfMarket = fIceEfMarket;
	}
	@Column(name="FICE_US_MarketFee")
	public String getFIceUsMarketFee() {
		return FIceUsMarketFee;
	}
	public void setFIceUsMarketFee(String fIceUsMarketFee) {
		FIceUsMarketFee = fIceUsMarketFee;
	}
	@Column(name="FICE_EC_MarketFee")
	public String getFIceEcMarketFee() {
		return FIceEcMarketFee;
	}
	public void setFIceEcMarketFee(String fIceEcMarketFee) {
		FIceEcMarketFee = fIceEcMarketFee;
	}
	@Column(name="FICE_EF_MarketFee")
	public String getFIceEfMarketFee() {
		return FIceEfMarketFee;
	}
	public void setFIceEfMarketFeee(String fIceEfMarketFee) {
		FIceEfMarketFee = fIceEfMarketFee;
	}
	@Column(name="FICE_MarketFeeWay")
	public String getFIceMarketFeeWay() {
		return FIceMarketFeeWay;
	}
	public void setFIceMarketFeeWayy(String fIceMarketFeeWay) {
		FIceMarketFeeWay = fIceMarketFeeWay;
	}
	@Column(name="FRiskLevel")
	public String getFRiskLevel() {
		return FRiskLevel;
	}
	public void setFRiskLevel(String fRiskLevel) {
		FRiskLevel = fRiskLevel;
	}
	@Column(name="FAsset")
	public String getFAsset() {
		return FAsset;
	}
	public void setFAsset(String fAsset) {
		FAsset = fAsset;
	}
	@Column(name="FOpenName")
	public String getFOpenName() {
		return FOpenName;
	}
	public void setFOpenName(String fOpenName) {
		FOpenName = fOpenName;
	}
	@Column(name="FOpenIdentity")
	public String getFOpenIdentity() {
		return FOpenIdentity;
	}
	public void setFOpenIdentityy(String fOpenIdentity) {
		FOpenIdentity = fOpenIdentity;
	}
	@Column(name="FShareHolder")
	public String getFShareHolder() {
		return FShareHolder;
	}
	public void setFShareHolder(String fShareHolder) {
		FShareHolder = fShareHolder;
	}
	@Column(name="FShareCapital")
	public String getFShareCapital() {
		return FShareCapital;
	}
	public void setFShareCapital(String fShareCapital) {
		FShareCapital = fShareCapital;
	}
	@Column(name="FRegisteredAddress")
	public String getFRegisteredAddress() {
		return FRegisteredAddress;
	}
	public void setFRegisteredAddress(String fRegisteredAddress) {
		FRegisteredAddress = fRegisteredAddress;
	}
	@Column(name="FAPIOpenTime")
	public String getFApiopenTime() {
		return FApiopenTime;
	}
	public void setFApiopenTime(String fApiopenTime) {
		FApiopenTime = fApiopenTime;
	}
	@Column(name="FAPICloseTime")
	public String getFApicloseTime() {
		return FApicloseTime;
	}
	public void setFApicloseTime(String fApicloseTime) {
		FApicloseTime = fApicloseTime;
	}
	@Column(name="FNationality")
	public String getFNationality() {
		return FNationality;
	}
	public void setFNationality(String fNationality) {
		FNationality = fNationality;
	}
	@Column(name="FUseSpan")
	public String getFUseSpan() {
		return FUseSpan;
	}
	public void setFUseSpan(String fUseSpan) {
		FUseSpan = fUseSpan;
	}
	@Column(name="FHKEX_Marcket")
	public String getFHkexMarcket() {
		return FHkexMarcket;
	}
	public void setFHkexMarcket(String fHkexMarcket) {
		FHkexMarcket = fHkexMarcket;
	}
	@Column(name="FHKEX_MarketFee")
	public String getFHkexMarketFee() {
		return FHkexMarketFee;
	}
	public void setFHkexMarketFee(String fHkexMarketFee) {
		FHkexMarketFee = fHkexMarketFee;
	}
	@Column(name="ModifyDate")
	public String getMOdifyDate() {
		return MOdifyDate;
	}
	public void setMOdifyDate(String mOdifyDate) {
		MOdifyDate = mOdifyDate;
	}
	@Column(name="FOpenType")
	public String getFOpenType() {
		return FOpenType;
	}
	public void setFOpenType(String fOpenType) {
		FOpenType = fOpenType;
	}
	@Column(name="FClientQuestion")
	public String getFClientQuestion() {
		return FClientQuestion;
	}
	public void setFClientQuestion(String fClientQuestion) {
		FClientQuestion = fClientQuestion;
	}
	@Column(name="FClientAnswer")
	public String getFClientAnswer() {
		return FClientAnswer;
	}
	public void setFClientAnswer(String fClientAnswer) {
		FClientAnswer = fClientAnswer;
	}

	
}
