package com.zd.crmbatch.business.entity;
// default package
// Generated 2018-4-20 9:30:53 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TcoverId generated by hbm2java
 */
@Table(name="TCover")
@Entity
public class TCover{

	private int FSerialId;
	private String fDate;
	private String FOpenDate;
	private String FCoverDate;
	private String FClientNo;
	private String FOpenNo;
	private String FCoverNo;
	private String FExchangeNo;
	private String FCommodityNo;
	private String FContractNo;
	private String FCoverDirect;
	private Integer FCoverVol;
	private BigDecimal FOpenPrice;
	private BigDecimal FCoverPrice;
	private BigDecimal FCoverProfit;
	private String FUpperNo;
	private String FGroupNo;
	private String FCurrencyNo;
	
	@Id
	@Column(name="FSerialId")
	public int getFSerialId() {
		return FSerialId;
	}
	public void setFSerialId(int fSerialId) {
		FSerialId = fSerialId;
	}
	@Column(name="FDate")
	public String getfDate() {
		return fDate;
	}
	public void setfDate(String fDate) {
		this.fDate = fDate;
	}
	@Column(name="FOpenDate")
	public String getFOpenDate() {
		return FOpenDate;
	}
	public void setFOpenDate(String fOpenDate) {
		FOpenDate = fOpenDate;
	}
	@Column(name="FCoverDate")
	public String getFCoverDate() {
		return FCoverDate;
	}
	public void setFCoverDate(String fCoverDate) {
		FCoverDate = fCoverDate;
	}
	@Column(name="FClientNo")
	public String getFClientNo() {
		return FClientNo;
	}
	public void setFClientNo(String fClientNo) {
		FClientNo = fClientNo;
	}
	@Column(name="FOpenNo")
	public String getFOpenNo() {
		return FOpenNo;
	}
	public void setFOpenNo(String fOpenNo) {
		FOpenNo = fOpenNo;
	}
	@Column(name="FCoverNo")
	public String getFCoverNo() {
		return FCoverNo;
	}
	public void setFCoverNo(String fCoverNo) {
		FCoverNo = fCoverNo;
	}
	@Column(name="FExchangeNo")
	public String getFExchangeNo() {
		return FExchangeNo;
	}
	public void setFExchangeNo(String fExchangeNo) {
		FExchangeNo = fExchangeNo;
	}
	@Column(name="FCommodityNo")
	public String getFCommodityNo() {
		return FCommodityNo;
	}
	public void setFCommodityNo(String fCommodityNo) {
		FCommodityNo = fCommodityNo;
	}
	@Column(name="FContractNo")
	public String getFContractNo() {
		return FContractNo;
	}
	public void setFContractNo(String fContractNo) {
		FContractNo = fContractNo;
	}
	@Column(name="FCoverDirect")
	public String getFCoverDirect() {
		return FCoverDirect;
	}
	public void setFCoverDirect(String fCoverDirect) {
		FCoverDirect = fCoverDirect;
	}
	@Column(name="FCoverVol")
	public Integer getFCoverVol() {
		return FCoverVol;
	}
	public void setFCoverVol(Integer fCoverVol) {
		FCoverVol = fCoverVol;
	}
	@Column(name="FOpenPrice")
	public BigDecimal getFOpenPrice() {
		return FOpenPrice;
	}
	public void setFOpenPrice(BigDecimal fOpenPrice) {
		FOpenPrice = fOpenPrice;
	}
	@Column(name="FCoverPrice")
	public BigDecimal getFCoverPrice() {
		return FCoverPrice;
	}
	public void setFCoverPrice(BigDecimal fCoverPrice) {
		FCoverPrice = fCoverPrice;
	}
	@Column(name="FCoverProfit")
	public BigDecimal getFCoverProfit() {
		return FCoverProfit;
	}
	public void setFCoverProfit(BigDecimal fCoverProfit) {
		FCoverProfit = fCoverProfit;
	}
	@Column(name="FUpperNo")
	public String getFUpperNo() {
		return FUpperNo;
	}
	public void setFUpperNo(String fUpperNo) {
		FUpperNo = fUpperNo;
	}
	@Column(name="FGroupNo")
	public String getFGroupNo() {
		return FGroupNo;
	}
	public void setFGroupNo(String fGroupNo) {
		FGroupNo = fGroupNo;
	}
	@Column(name="FCurrencyNo")
	public String getFCurrencyNo() {
		return FCurrencyNo;
	}
	public void setFCurrencyNo(String fCurrencyNo) {
		FCurrencyNo = fCurrencyNo;
	}


}
