package com.zd.crmbatch.business.entity;
// default package
// Generated 2018-4-20 9:30:53 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TorderId generated by hbm2java
 */
@Table(name="TOrder")
@Entity
public class TOrder{

	private int FSerialId;
	private String fDate;
	private Integer FRequestId;
	private String FOrderId;
	private String FSystemNo;
	private String FUpperNo;
	private String FClientNo;
	private String FInsertOperNo;
	private String FDeleteOperNo;
	private String FExchangeNo;
	private String FCommodityNo;
	private String FContractNo;
	private String FType;
	private String FIsRiskOrder;
	private String FDirect;
	private BigDecimal FOrderPrice;
	private BigDecimal FOrderPrice2;
	private Integer FOrderVol;
	private BigDecimal FMatchPrice;
	private Integer FMatchVol;
	private String FState;
	private Integer FStateCode;
	private Integer FStreamId;
	private Integer FUpperStreamId;
	private String FInsertDateTime;
	private String FDeleteDateTime;
	private String FOrderWay;
	private String FInputNo;
	private String FPriceType;
	private String FFlid;
	private String FUpperOrderId;
	private String FIsValid;
	private Integer FModifyVol;
	private BigDecimal FModifyPrice;
	private BigDecimal FModifyPrice2;
	private String FStrategyId;
	private String FOffset;
	private String FSubClientNo;
	private Integer FMaxShow;
	private Integer FMinQty;
	private String FClientSystemNo;
	private String FLocalInsertDateTime;
	private String FLocalUpdateDateTime;
	
	@Id
	@Column(name="FSerialId")
	public int getFSerialId() {
		return FSerialId;
	}
	public void setFSerialId(int fSerialId) {
		FSerialId = fSerialId;
	}
	@Column(name="FDate")
	public String getfDate() {
		return fDate;
	}
	public void setfDate(String fDate) {
		this.fDate = fDate;
	}
	@Column(name="FRequestId")
	public Integer getFRequestId() {
		return FRequestId;
	}
	public void setFRequestId(Integer fRequestId) {
		FRequestId = fRequestId;
	}
	@Column(name="FOrderId")
	public String getFOrderId() {
		return FOrderId;
	}
	public void setFOrderId(String fOrderId) {
		FOrderId = fOrderId;
	}
	@Column(name="FSystemNo")
	public String getFSystemNo() {
		return FSystemNo;
	}
	public void setFSystemNo(String fSystemNo) {
		FSystemNo = fSystemNo;
	}
	@Column(name="FUpperNo")
	public String getFUpperNo() {
		return FUpperNo;
	}
	public void setFUpperNo(String fUpperNo) {
		FUpperNo = fUpperNo;
	}
	@Column(name="FClientNo")
	public String getFClientNo() {
		return FClientNo;
	}
	public void setFClientNo(String fClientNo) {
		FClientNo = fClientNo;
	}
	@Column(name="FInsertOperNo")
	public String getFInsertOperNo() {
		return FInsertOperNo;
	}
	public void setFInsertOperNo(String fInsertOperNo) {
		FInsertOperNo = fInsertOperNo;
	}
	@Column(name="FDeleteOperNo")
	public String getFDeleteOperNo() {
		return FDeleteOperNo;
	}
	public void setFDeleteOperNo(String fDeleteOperNo) {
		FDeleteOperNo = fDeleteOperNo;
	}
	@Column(name="FExchangeNo")
	public String getFExchangeNo() {
		return FExchangeNo;
	}
	public void setFExchangeNo(String fExchangeNo) {
		FExchangeNo = fExchangeNo;
	}
	@Column(name="FCommodityNo")
	public String getFCommodityNo() {
		return FCommodityNo;
	}
	public void setFCommodityNo(String fCommodityNo) {
		FCommodityNo = fCommodityNo;
	}
	@Column(name="FContractNo")
	public String getFContractNo() {
		return FContractNo;
	}
	public void setFContractNo(String fContractNo) {
		FContractNo = fContractNo;
	}
	@Column(name="FType")
	public String getFType() {
		return FType;
	}
	public void setFType(String fType) {
		FType = fType;
	}
	@Column(name="FIsRiskOrder")
	public String getFIsRiskOrder() {
		return FIsRiskOrder;
	}
	public void setFIsRiskOrder(String fIsRiskOrder) {
		FIsRiskOrder = fIsRiskOrder;
	}
	@Column(name="FDirect")
	public String getFDirect() {
		return FDirect;
	}
	public void setFDirect(String fDirect) {
		FDirect = fDirect;
	}
	@Column(name="FOrderPrice")
	public BigDecimal getFOrderPrice() {
		return FOrderPrice;
	}
	public void setFOrderPrice(BigDecimal fOrderPrice) {
		FOrderPrice = fOrderPrice;
	}
	@Column(name="FOrderPrice2")
	public BigDecimal getFOrderPrice2() {
		return FOrderPrice2;
	}
	public void setFOrderPrice2(BigDecimal fOrderPrice2) {
		FOrderPrice2 = fOrderPrice2;
	}
	@Column(name="FOrderVol")
	public Integer getFOrderVol() {
		return FOrderVol;
	}
	public void setFOrderVol(Integer fOrderVol) {
		FOrderVol = fOrderVol;
	}
	@Column(name="FMatchPrice")
	public BigDecimal getFMatchPrice() {
		return FMatchPrice;
	}
	public void setFMatchPrice(BigDecimal fMatchPrice) {
		FMatchPrice = fMatchPrice;
	}
	@Column(name="FMatchVol")
	public Integer getFMatchVol() {
		return FMatchVol;
	}
	public void setFMatchVol(Integer fMatchVol) {
		FMatchVol = fMatchVol;
	}
	@Column(name="FState")
	public String getFState() {
		return FState;
	}
	public void setFState(String fState) {
		FState = fState;
	}
	@Column(name="FStateCode")
	public Integer getFStateCode() {
		return FStateCode;
	}
	public void setFStateCode(Integer fStateCode) {
		FStateCode = fStateCode;
	}
	@Column(name="FStreamId")
	public Integer getFStreamId() {
		return FStreamId;
	}
	public void setFStreamId(Integer fStreamId) {
		FStreamId = fStreamId;
	}
	@Column(name="FUpperStreamId")
	public Integer getFUpperStreamId() {
		return FUpperStreamId;
	}
	public void setFUpperStreamId(Integer fUpperStreamId) {
		FUpperStreamId = fUpperStreamId;
	}
	@Column(name="FInsertDateTime")
	public String getFInsertDateTime() {
		return FInsertDateTime;
	}
	public void setFInsertDateTime(String fInsertDateTime) {
		FInsertDateTime = fInsertDateTime;
	}
	@Column(name="FDeleteDateTime")
	public String getFDeleteDateTime() {
		return FDeleteDateTime;
	}
	public void setFDeleteDateTime(String fDeleteDateTime) {
		FDeleteDateTime = fDeleteDateTime;
	}
	@Column(name="FOrderWay")
	public String getFOrderWay() {
		return FOrderWay;
	}
	public void setFOrderWay(String fOrderWay) {
		FOrderWay = fOrderWay;
	}
	@Column(name="FInputNo")
	public String getFInputNo() {
		return FInputNo;
	}
	public void setFInputNo(String fInputNo) {
		FInputNo = fInputNo;
	}
	@Column(name="FPriceType")
	public String getFPriceType() {
		return FPriceType;
	}
	public void setFPriceType(String fPriceType) {
		FPriceType = fPriceType;
	}
	@Column(name="FFlid")
	public String getFFlid() {
		return FFlid;
	}
	public void setFFlid(String fFlid) {
		FFlid = fFlid;
	}
	@Column(name="FUpperOrderId")
	public String getFUpperOrderId() {
		return FUpperOrderId;
	}
	public void setFUpperOrderId(String fUpperOrderId) {
		FUpperOrderId = fUpperOrderId;
	}
	@Column(name="FIsValid")
	public String getFIsValid() {
		return FIsValid;
	}
	public void setFIsValid(String fIsValid) {
		FIsValid = fIsValid;
	}
	@Column(name="FModifyVol")
	public Integer getFModifyVol() {
		return FModifyVol;
	}
	public void setFModifyVol(Integer fModifyVol) {
		FModifyVol = fModifyVol;
	}
	@Column(name="FModifyPrice")
	public BigDecimal getFModifyPrice() {
		return FModifyPrice;
	}
	public void setFModifyPrice(BigDecimal fModifyPrice) {
		FModifyPrice = fModifyPrice;
	}
	@Column(name="FModifyPrice2")
	public BigDecimal getFModifyPrice2() {
		return FModifyPrice2;
	}
	public void setFModifyPrice2(BigDecimal fModifyPrice2) {
		FModifyPrice2 = fModifyPrice2;
	}
	@Column(name="FStrategyId")
	public String getFStrategyId() {
		return FStrategyId;
	}
	public void setFStrategyId(String fStrategyId) {
		FStrategyId = fStrategyId;
	}
	@Column(name="FOffset")
	public String getFOffset() {
		return FOffset;
	}
	public void setFOffset(String fOffset) {
		FOffset = fOffset;
	}
	@Column(name="FSubClientNo")
	public String getFSubClientNo() {
		return FSubClientNo;
	}
	public void setFSubClientNo(String fSubClientNo) {
		FSubClientNo = fSubClientNo;
	}
	@Column(name="FMaxShow")
	public Integer getFMaxShow() {
		return FMaxShow;
	}
	public void setFMaxShow(Integer fMaxShow) {
		FMaxShow = fMaxShow;
	}
	@Column(name="FMinQty")
	public Integer getFMinQty() {
		return FMinQty;
	}
	public void setFMinQty(Integer fMinQty) {
		FMinQty = fMinQty;
	}
	@Column(name="FClientSystemNo")
	public String getFClientSystemNo() {
		return FClientSystemNo;
	}
	public void setFClientSystemNo(String fClientSystemNo) {
		FClientSystemNo = fClientSystemNo;
	}
	@Column(name="FLocalInsertDateTime")
	public String getFLocalInsertDateTime() {
		return FLocalInsertDateTime;
	}
	public void setFLocalInsertDateTime(String fLocalInsertDateTime) {
		FLocalInsertDateTime = fLocalInsertDateTime;
	}
	@Column(name="FLocalUpdateDateTime")
	public String getFLocalUpdateDateTime() {
		return FLocalUpdateDateTime;
	}
	public void setFLocalUpdateDateTime(String fLocalUpdateDateTime) {
		FLocalUpdateDateTime = fLocalUpdateDateTime;
	}


}
